name: Run Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    name: "Test"
    runs-on: windows-latest

    defaults:
      run:
        shell: 'msys2 {0}'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: FFMS/ffms2
        path: ffms2

    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          autotools
          mingw-w64-x86_64-ffmpeg
          mingw-w64-x86_64-toolchain
          python

    - name: Run test.py
      run: |
        python3 test.py
